### ISSUE TITLE
[Sleek] Playback bar offset when listening on another device

### ISSUE THREAD

**Issue by ajmeese7** [spicetify/spicetify-themes#863]
**Describe the bug**

When listening on another device, the playback bar is offset way off of where it is supposed to be.

**Expected behavior**

The playback bar should display in the same spot that it normally displays.

**Screenshots**

![Playback bar is offset](https://user-images.githubusercontent.com/17814535/202856637-a5a682a4-d3bb-41a8-8ff2-80d6d6836b46.png)

**Logs**

![Console logs](https://user-images.githubusercontent.com/17814535/202856777-5bc7e6a1-cbc9-464a-8b20-e065d5f0c930.png)

**Specifics (please complete the following information):**
 - OS: ZorinOS 16 Pro
 - Spotify version: 1.1.84.716.gc5f8b819
 - Spicetify version: 2.14.1
 - Theme name: Sleek (Color scheme is Elementary)

**Comment by harbassan** [comment]
should be fixed now.

**Comment by ajmeese7** [comment]
I've created a PR follow-up to bf288f8d226f1528a4a91a86fde2687c1a3d8035 in #885, since the original commit didn't resolve the issue for me.
