### ISSUE TITLE
Layout broken on spicetify 2.20.0

### ISSUE THREAD

**Issue by MonsieurDupont** [spicetify/spicetify-themes#950]
This is what the theme looks like right after installing it with no other extensions or bribes installed 
![image](https://github.com/spicetify/spicetify-themes/assets/122630849/3fb97f7a-efa0-40bf-8778-094acf36c7f6)

How can I fix this?

**Comment by auroraisluna** [comment]
Can confirm this happens on Dribbblish too

![image](https://github.com/spicetify/spicetify-themes/assets/98479040/45f65c0e-8f51-45e1-9e47-77452f1bd4d2)

**Comment by harbassan** [comment]
working on it right now

**Comment by harbassan** [comment]
should be fixed now

**Comment by MonsieurDupont** [comment]
Still broken for me, I think it's because of the new spotify version that rolled out today (i belive)
![image](https://github.com/spicetify/spicetify-themes/assets/122630849/9ba18322-02f3-4a93-8930-2aff91205d2a)
